version: "3"

services:
  endpoint:
    build: 
      context: .
    container_name: endpoint
    ports: 
      - 4000:4000
    command: mix run
    tty: true
    depends_on: 
      - db
    networks:
      - postgres
  db:
    image: postgres:9.6
    container_name: db
    environment:
      - POSTGRES_DB=desafio_contai
      - POSTGRES_USER=desafio_contai
      - POSTGRES_PASSWORD=desafio_contai
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

